### ISSUE TITLE
Is the current API repetitive?

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/getopts#44]
No intentions to release a new major soon, but I'd like to leave the question here lest I forget.

Don't you feel the current API is repetitive? We could trade less repetition for some verbosity:

```js
getopts(process.argv.slice(2), {
  options: {
    foo: {
      alias: ["f", "F"],
      boolean: true,
      default: false
    },
    bar: {
      default: 42
    },
    baz: {
      alias: ["B", "bazmut"],
      string: true,
      default: "hello"
    }
  },
  stopEarly: true
})
```

For comparison, here's how you'd do it using the current API:

```js
getopts(process.argv.slice(2), {
  alias: {
    foo: ["f", "F"],
    baz: ["B", "bazmut"]
  },
  default: {
    foo: false,
    bar: 42,
    baz: "hello"
  },
  boolean: ["foo"],
  stopEarly: true
})
```

**Comment by dirkbonhomme** [comment]
I like that idea

**Comment by tcrowe** [comment]
Hey @jorgebucaran 👋  I'm getting some good use out of it. I'm happy as-is but I will adjust if you change it. TY contributors 😍

**Comment by thiagodp** [comment]
@jorgebucaran I would keep the current API and create a separate package that converts the "verbose" format to the current.

**Comment by jorgebucaran** [comment]
Thank you for the suggestion @thiagodp, that makes sense to me as well.

**Comment by jorgebucaran** [comment]
It's been a while here, and I don't think we're going to be changing the API at this point. This issue has run its course. 👋
