### ISSUE TITLE
Result differs from yargs

### ISSUE THREAD

**Issue by ndabAP** [jorgebucaran/getopts#45]
Hey!

I've built a [Vue.js terminal emulator](https://github.com/ndabAP/vue-command) and switched recently from `yargs` to `getops`. Now a user of my library comes up with this issue: https://github.com/ndabAP/vue-command/issues/176

I thought I just propagate it and see if you can say something to it.

**Comment by jorgebucaran** [comment]
@ndabAP Hey! Hmm, it could be a bug in getopts, but I can't reproduce any issues with white space:

```js
#!/usr/bin/env node

const getopts = require("getopts")
console.log(getopts(process.argv.slice(2)))
```
```console
./example --foo="a b c" --bar "a b c"
```
```js
{ _: [], foo: 'a b c', bar: 'a b c' }
```

Can you clarify the problem?

**Comment by jorgebucaran** [comment]
@ndabAP Hmm, [here](https://github.com/ndabAP/vue-command/blob/6f19260da4413a956933be0dbc5d90a9f77797c6/src/hosted/App.vue#L159), I found that `stdin` is:

```console
reverse "a b c"
```

And `stdin.split(' ')[1]` will not give you the rest of the string. Instead we need to do this:

```js
const argument = stdin.split(' ').slice(1).join(' ')
```

or 

```js
const argument = stdin.split(' ').slice(1).join(' ').replace(/"/g, '')
```

(if you also want to get rid of `"`s.)

I tried it here and it works now! Please reopen if you need help with anything else. 👋 

<img width="1440" alt="スクリーンショット 2020-06-12 17 28 49" src="https://user-images.githubusercontent.com/56996/84482362-8d2f0500-acd2-11ea-8731-9917d070c83c.png">

**Comment by ndabAP** [comment]
You are simply awesome!
