### ISSUE TITLE
Question about short options

### ISSUE THREAD

**Issue by thiagodp** [jorgebucaran/getopts#49]
- `-w9` results in `{"w": 9}`
- Shouldn't `-w=9` result in `"w":9` ? It gives `{"w": "=9"}`
- Is it a library option or some kind of convention?

Users usually expect that a short option behaves like a long one. Example:
- ` --script-file="f1.js,f2.js"` →  `{"script-file": "f1.js,f2.js"}`
- ` -F="f1.js,f2.js"` → `{"F": "=f1.js,f2.js"}` (`=` is added to the content)

Users are obligated to use a space (`-F "f1.js,f2.js"`) to have the same effect. Isn't it an inconsistency in the expected interface? I mean, _wouldn't be better to detect the equal sign as a value separator for short options_?

**Comment by jorgebucaran** [comment]
> @thiagodp Is it a library option or some kind of convention?

It's my interpretation of https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html. 

For example take this C program:

```c
#include <stdio.h>
#include <stdlib.h>
#include <getopt.h>

int main (int argc, char **argv) {
  while (1) {
    static struct option long_options[] = {
        {"file", required_argument, 0, 'f'},
        {0, 0, 0, 0}
      };
    int option_index = 0;

    switch (getopt_long(argc, argv, "f:", long_options, &option_index)) {
    case 'f':
      printf("File is: `%s'\n", optarg);
      break;

    default:
      exit(0);
    }
  }
}
```
```console
./main --file=foo.js
File is `foo.js'

./main --file foo.js
File is `foo.js'

./main -f foo.js
File is `foo.js'

./main -f=foo.js 
File is: `=foo.js' # (ಠ益ಠ)
```

>  Isn't it a inconsistency in the expected interface? Wouldn't be better to detect the equal sign as a value separator for short options?

💯 Totally! And it would simplify getopts a lot if we could get rid of all the historical baggage! But my goal is to be mostly consistent with traditional UNIX. That's why the source is so full of gotchas.

**Comment by thiagodp** [comment]
Okay. Thank you again 😊👍
