### ISSUE TITLE
ESM imports support

### ISSUE THREAD

**Issue by v1rtl** [jorgebucaran/getopts#52]
Would be cool to have an ESM version of `getopts`, so we can use named imports in Node with this module.

**Comment by jorgebucaran** [comment]
@talentlessguy Absolutely. And yes, I'm actually (already) working on this, I'm just caught up in maintenance hell right now. 😄

**Comment by jorgebucaran** [comment]
ES module support is now available (7d79cbf775cf985f22cda0029e73ed72e7c9c50e). 💯
