### ISSUE TITLE
Built-in TypeScript support and autogeneration of arguments, based on params

### ISSUE THREAD

**Issue by o-alexandrov** [jorgebucaran/getopts#56]
1. Add TypeScript typings
2. Autogenerate arguments typings (so-called type inference) based on the supplied params.

<details><summary>A similar solution with yargs</summary>

This feature should be built-in for type safety.

```ts
export const builder = {
  dynamodb: {
    type: `boolean`,
    default: false,
    describe: `Set up local dynamodb instance`,
  },
  clearPorts: {
    type: `array`,
    default: [],
    describe: `Remove processes from the specified Ports Number[]`,
  },
} as const
type builder = typeof builder
type cmds = keyof builder
type getType<key extends cmds> = builder[key]["type"] extends "string"
  ? string
  : builder[key]["type"] extends "boolean"
  ? boolean
  : builder[key]["type"] extends "number"
  ? number
  : builder[key]["type"] extends "array"
  ? any[]
  : unknown
export type yargsArguments = {
  [key in cmds]: getType<key>
}
```

<img width="702" alt="Screen Shot 2021-06-07 at 9 13 15 AM" src="https://user-images.githubusercontent.com/9992724/121032143-9f6e4280-c770-11eb-9dfe-c268011beaa8.png">

</details>

**Comment by jorgebucaran** [comment]
Do you want to work on this?

**Comment by o-alexandrov** [comment]
Unfortunately, I can’t. Reporting here as a feature request

**Comment by jorgebucaran** [comment]
We already have typings, no?
