### ISSUE TITLE
Add an option to remove duplicate items from the `options` array

### ISSUE THREAD

**Issue by tukusejssirs** [jorgebucaran/getopts#57]
IMHO, the output of `getopts()` should contain only one value per option. If one sets an alias, currently it creates two items in the array (e.g. `h` and `help`), while I think it should be only one (usually `help`).

I suggest to add an option to create an array with only either long or short options. If an option would not have set an alias, it would add it nevertheless.

**Comment by jorgebucaran** [comment]
Care to show me an example of what you mean? 😄

**Comment by tukusejssirs** [comment]
This object:

```js
const options = getopts(process.argv.slice(2), {
  alias: {
    help: 'h',
    file: 'f'
  }
}
```

when running this:

```bash
./program.js -h -f file -t --whatever

would contain instead of this:

```js
{
  _: [],
  h: true,
  help: true,
  f: 'file',
  file: 'file',
  t: true,
  whatever: true
}
```

this:

```js
{
  _: [],
  help: true,
  file: 'file',
  t: true,
  whatever: true
}
```

**Comment by jorgebucaran** [comment]
How does the current output of getopts prevents you from carrying out what you are trying to do (whatever that is)?

**Comment by tukusejssirs** [comment]
Sorry, I’ve been caught up by work.

> How does the current output of getopts prevents you from carrying out what you are trying to do (whatever that is)?

It does not prevent me from carrying out anything, I just think that having all those properties twice is useless and consumes (let’s say) twice the space in the memory. YMMV.
